# This workflow will build and push a web application to an Azure Static Web App when you change your code
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 2. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks

name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
      #- COPS-1857-cicd-poc # TODO after testing, enable master and delete this
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      #- COPS-1857-cicd-poc # TODO after testing, enable master and delete this

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "sm4-filemanager-frontend" # App source code path relative to repository root
  API_LOCATION: "sm4-filemanager-frontend/api" # Api source code path relative to repository root - optional
  APP_ARTIFACT_LOCATION: "public" # Built app content directory, relative to app_location - optional
  
permissions:
  contents: read

jobs:
    build_and_deploy_job_test:
        permissions:
          contents: read # for actions/checkout to fetch code
          pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
        if: endswith(github.ref, 'origtest') && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
        runs-on: ubuntu-latest
        environment: dev
        name: Build and deploy job for test environment
        strategy:
          matrix:
            node-version: [14.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
          - uses: actions/checkout@v3
            with:
                submodules: true
                repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'    
              cache-dependency-path: sm4-filemanager-frontend/package-lock.json
          - working-directory: ./sm4-filemanager-frontend
            run: npm ci
          - working-directory: ./sm4-filemanager-frontend
            run: npm run build
          - name: Deploy to test
            id: deploytest
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
              action: "upload"
              app_location: ${{ env.APP_LOCATION }}
              api_location: ${{ env.API_LOCATION }}
              app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          - name: Deploy to prod
            id: deployprod
            if: success() && endswith(github.ref, 'master')
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
              action: "upload"
              app_location: ${{ env.APP_LOCATION }}
              api_location: ${{ env.API_LOCATION }}
              app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          - name: Deploy to dev
            id: deploydev
            if: "!contains(github.ref,'master')"
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
              action: "upload"
              app_location: ${{ env.APP_LOCATION }}
              api_location: ${{ env.API_LOCATION }}
              app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}

    build_and_deploy_job_prod:
        permissions:
          contents: read # for actions/checkout to fetch code
          pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
        needs: build_and_deploy_job_test    
        if: success() && endswith(github.ref, 'master') && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed'))
        runs-on: ubuntu-latest
        environment: test
        name: Build and deploy job for production environment
        strategy:
          matrix:
            node-version: [14.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
          - uses: actions/checkout@v3
            with:
                submodules: true
                repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'    
              cache-dependency-path: sm4-filemanager-frontend/package-lock.json
          - working-directory: ./sm4-filemanager-frontend
            run: npm ci
          - working-directory: ./sm4-filemanager-frontend
            run: npm run build
          - name: Deploy to prod
            id: deployprod
            uses: Azure/static-web-apps-deploy@v1
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
              action: "upload"
              app_location: ${{ env.APP_LOCATION }}
              api_location: ${{ env.API_LOCATION }}
              app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
    
    close_pull_request_job:
      runs-on: ubuntu-latest
      permissions:
        contents: none
      if: github.event_name == 'pull_request' && github.event.action == 'closed'   
      name: Close Pull Request Job
      steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
